// Code generated by goctl. DO NOT EDIT.
package types

type RaffleAwardListRequest struct {
	StrategyId int64 `json:"strategy_id"`
}

type RaffleAwardListResponse struct {
	AwardId       int    `json:"award_id"`
	AwardTitle    string `json:"award_title"`
	AwardSubtitle int    `json:"award_subtitle"`
	Sort          int    `json:"sort"`
}

type RaffleRequest struct {
	StrategyId int64 `json:"strategy_id"`
}

type RaffleResponse struct {
	AwardId    int `json:"award_id"`
	AwardIndex int `json:"award_index"`
}

type StrategyArmoryRequest struct {
	StrategyId int64 `json:"strategy_id"`
}

type StrategyArmoryResponse struct {
	IsSuccess bool `json:"is_success"`
}
