// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	ruleTreeNodeLineFieldNames          = builder.RawFieldNames(&RuleTreeNodeLine{})
	ruleTreeNodeLineRows                = strings.Join(ruleTreeNodeLineFieldNames, ",")
	ruleTreeNodeLineRowsExpectAutoSet   = strings.Join(stringx.Remove(ruleTreeNodeLineFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	ruleTreeNodeLineRowsWithPlaceHolder = strings.Join(stringx.Remove(ruleTreeNodeLineFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheBigMarketRuleTreeNodeLineIdPrefix = "cache:bigMarket:ruleTreeNodeLine:id:"
)

type (
	ruleTreeNodeLineModel interface {
		Insert(ctx context.Context, data *RuleTreeNodeLine) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*RuleTreeNodeLine, error)
		Update(ctx context.Context, data *RuleTreeNodeLine) error
		Delete(ctx context.Context, id int64) error
	}

	defaultRuleTreeNodeLineModel struct {
		sqlc.CachedConn
		table string
	}

	RuleTreeNodeLine struct {
		Id             int64     `db:"id"`               // 自增ID
		TreeId         string    `db:"tree_id"`          // 规则树ID
		RuleNodeFrom   string    `db:"rule_node_from"`   // 规则Key节点 From
		RuleNodeTo     string    `db:"rule_node_to"`     // 规则Key节点 To
		RuleLimitType  string    `db:"rule_limit_type"`  // 限定类型；1:=;2:>;3:<;4:>=;5<=;6:enum[枚举范围];
		RuleLimitValue string    `db:"rule_limit_value"` // 限定值（到下个节点）
		CreateTime     time.Time `db:"create_time"`      // 创建时间
		UpdateTime     time.Time `db:"update_time"`      // 更新时间
	}
)

func newRuleTreeNodeLineModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultRuleTreeNodeLineModel {
	return &defaultRuleTreeNodeLineModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`rule_tree_node_line`",
	}
}

func (m *defaultRuleTreeNodeLineModel) Delete(ctx context.Context, id int64) error {
	bigMarketRuleTreeNodeLineIdKey := fmt.Sprintf("%s%v", cacheBigMarketRuleTreeNodeLineIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, bigMarketRuleTreeNodeLineIdKey)
	return err
}

func (m *defaultRuleTreeNodeLineModel) FindOne(ctx context.Context, id int64) (*RuleTreeNodeLine, error) {
	bigMarketRuleTreeNodeLineIdKey := fmt.Sprintf("%s%v", cacheBigMarketRuleTreeNodeLineIdPrefix, id)
	var resp RuleTreeNodeLine
	err := m.QueryRowCtx(ctx, &resp, bigMarketRuleTreeNodeLineIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", ruleTreeNodeLineRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRuleTreeNodeLineModel) Insert(ctx context.Context, data *RuleTreeNodeLine) (sql.Result, error) {
	bigMarketRuleTreeNodeLineIdKey := fmt.Sprintf("%s%v", cacheBigMarketRuleTreeNodeLineIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, ruleTreeNodeLineRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TreeId, data.RuleNodeFrom, data.RuleNodeTo, data.RuleLimitType, data.RuleLimitValue)
	}, bigMarketRuleTreeNodeLineIdKey)
	return ret, err
}

func (m *defaultRuleTreeNodeLineModel) Update(ctx context.Context, data *RuleTreeNodeLine) error {
	bigMarketRuleTreeNodeLineIdKey := fmt.Sprintf("%s%v", cacheBigMarketRuleTreeNodeLineIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, ruleTreeNodeLineRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.TreeId, data.RuleNodeFrom, data.RuleNodeTo, data.RuleLimitType, data.RuleLimitValue, data.Id)
	}, bigMarketRuleTreeNodeLineIdKey)
	return err
}

func (m *defaultRuleTreeNodeLineModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheBigMarketRuleTreeNodeLineIdPrefix, primary)
}

func (m *defaultRuleTreeNodeLineModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", ruleTreeNodeLineRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultRuleTreeNodeLineModel) tableName() string {
	return m.table
}
