// Code generated by goctl. DO NOT EDIT.

package test

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	testFieldNames          = builder.RawFieldNames(&Test{})
	testRows                = strings.Join(testFieldNames, ",")
	testRowsExpectAutoSet   = strings.Join(stringx.Remove(testFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	testRowsWithPlaceHolder = strings.Join(stringx.Remove(testFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheBigMarketTestIdPrefix = "cache:bigMarket:test:id:"
)

type (
	testModel interface {
		Insert(ctx context.Context, data *Test) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Test, error)
		Update(ctx context.Context, data *Test) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTestModel struct {
		sqlc.CachedConn
		table string
	}

	Test struct {
		Id   int64          `db:"id"`
		Name sql.NullString `db:"name"`
	}
)

func newTestModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTestModel {
	return &defaultTestModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`test`",
	}
}

func (m *defaultTestModel) Delete(ctx context.Context, id int64) error {
	bigMarketTestIdKey := fmt.Sprintf("%s%v", cacheBigMarketTestIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, bigMarketTestIdKey)
	return err
}

func (m *defaultTestModel) FindOne(ctx context.Context, id int64) (*Test, error) {
	bigMarketTestIdKey := fmt.Sprintf("%s%v", cacheBigMarketTestIdPrefix, id)
	var resp Test
	err := m.QueryRowCtx(ctx, &resp, bigMarketTestIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", testRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTestModel) Insert(ctx context.Context, data *Test) (sql.Result, error) {
	bigMarketTestIdKey := fmt.Sprintf("%s%v", cacheBigMarketTestIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, testRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.Name)
	}, bigMarketTestIdKey)
	return ret, err
}

func (m *defaultTestModel) Update(ctx context.Context, data *Test) error {
	bigMarketTestIdKey := fmt.Sprintf("%s%v", cacheBigMarketTestIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, testRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Name, data.Id)
	}, bigMarketTestIdKey)
	return err
}

func (m *defaultTestModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheBigMarketTestIdPrefix, primary)
}

func (m *defaultTestModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", testRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTestModel) tableName() string {
	return m.table
}
