// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	ruleTreeFieldNames          = builder.RawFieldNames(&RuleTree{})
	ruleTreeRows                = strings.Join(ruleTreeFieldNames, ",")
	ruleTreeRowsExpectAutoSet   = strings.Join(stringx.Remove(ruleTreeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	ruleTreeRowsWithPlaceHolder = strings.Join(stringx.Remove(ruleTreeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheBigMarketRuleTreeIdPrefix     = "cache:bigMarket:ruleTree:id:"
	cacheBigMarketRuleTreeTreeIdPrefix = "cache:bigMarket:ruleTree:treeId:"
)

type (
	ruleTreeModel interface {
		Insert(ctx context.Context, data *RuleTree) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*RuleTree, error)
		FindOneByTreeId(ctx context.Context, treeId string) (*RuleTree, error)
		Update(ctx context.Context, data *RuleTree) error
		Delete(ctx context.Context, id int64) error
	}

	defaultRuleTreeModel struct {
		sqlc.CachedConn
		table string
	}

	RuleTree struct {
		Id              int64          `db:"id"`                 // 自增ID
		TreeId          string         `db:"tree_id"`            // 规则树ID
		TreeName        string         `db:"tree_name"`          // 规则树名称
		TreeDesc        sql.NullString `db:"tree_desc"`          // 规则树描述
		TreeNodeRuleKey string         `db:"tree_node_rule_key"` // 规则树根入口规则
		CreateTime      time.Time      `db:"create_time"`        // 创建时间
		UpdateTime      time.Time      `db:"update_time"`        // 更新时间
	}
)

func newRuleTreeModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultRuleTreeModel {
	return &defaultRuleTreeModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`rule_tree`",
	}
}

func (m *defaultRuleTreeModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	bigMarketRuleTreeIdKey := fmt.Sprintf("%s%v", cacheBigMarketRuleTreeIdPrefix, id)
	bigMarketRuleTreeTreeIdKey := fmt.Sprintf("%s%v", cacheBigMarketRuleTreeTreeIdPrefix, data.TreeId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, bigMarketRuleTreeIdKey, bigMarketRuleTreeTreeIdKey)
	return err
}

func (m *defaultRuleTreeModel) FindOne(ctx context.Context, id int64) (*RuleTree, error) {
	bigMarketRuleTreeIdKey := fmt.Sprintf("%s%v", cacheBigMarketRuleTreeIdPrefix, id)
	var resp RuleTree
	err := m.QueryRowCtx(ctx, &resp, bigMarketRuleTreeIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", ruleTreeRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRuleTreeModel) FindOneByTreeId(ctx context.Context, treeId string) (*RuleTree, error) {
	bigMarketRuleTreeTreeIdKey := fmt.Sprintf("%s%v", cacheBigMarketRuleTreeTreeIdPrefix, treeId)
	var resp RuleTree
	err := m.QueryRowIndexCtx(ctx, &resp, bigMarketRuleTreeTreeIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `tree_id` = ? limit 1", ruleTreeRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, treeId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRuleTreeModel) Insert(ctx context.Context, data *RuleTree) (sql.Result, error) {
	bigMarketRuleTreeIdKey := fmt.Sprintf("%s%v", cacheBigMarketRuleTreeIdPrefix, data.Id)
	bigMarketRuleTreeTreeIdKey := fmt.Sprintf("%s%v", cacheBigMarketRuleTreeTreeIdPrefix, data.TreeId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, ruleTreeRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TreeId, data.TreeName, data.TreeDesc, data.TreeNodeRuleKey)
	}, bigMarketRuleTreeIdKey, bigMarketRuleTreeTreeIdKey)
	return ret, err
}

func (m *defaultRuleTreeModel) Update(ctx context.Context, newData *RuleTree) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	bigMarketRuleTreeIdKey := fmt.Sprintf("%s%v", cacheBigMarketRuleTreeIdPrefix, data.Id)
	bigMarketRuleTreeTreeIdKey := fmt.Sprintf("%s%v", cacheBigMarketRuleTreeTreeIdPrefix, data.TreeId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, ruleTreeRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.TreeId, newData.TreeName, newData.TreeDesc, newData.TreeNodeRuleKey, newData.Id)
	}, bigMarketRuleTreeIdKey, bigMarketRuleTreeTreeIdKey)
	return err
}

func (m *defaultRuleTreeModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheBigMarketRuleTreeIdPrefix, primary)
}

func (m *defaultRuleTreeModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", ruleTreeRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultRuleTreeModel) tableName() string {
	return m.table
}
